stages:
  - predict
  - build

variables:
  API_URL: "https://mateo-charmless-velia.ngrok-free.dev"

prediction:
  stage: predict
  script:
    - |
      # GitLab appelle AUTOMATIQUEMENT l'API
      curl -s -X POST ${API_URL}/api/v1/ml/predict/simple \
        -H "Content-Type: application/json" \
        -d '{"pipeline_name": "'"${CI_PROJECT_NAME}"'", "source": "gitlab-ci", "duration": 300}'
  only:
    - main
    - develop

build:
  stage: build
  script:
    - echo "Build..."
  needs: ["prediction"]